### ISSUE TITLE
Using rest params?

### ISSUE THREAD

**Issue by donaldpipowitch** [leonardiwagner/z#3]
Nice lib! Docs say

> (x) => {} matches an array with a single element eg.: [1], [[1, 2, 3]] (array with a single array), matches single character eg.: 'x' or matches a single number eg.:1
(x, xs) => {} matches array with more than one element. First parameter is the first element (head), second is others (tail)

Couldn't we use rest params to be more precise? If `(x) => {}` matches _a single element_ I'd expect `(x, y) => {}` to match _exactly two elements_ (`array.length === 2`). I'd use `(x, ...xs) => {}` to match an array _with more than one element_ (first element (head) and others (tail)).

**Comment by leonardiwagner** [comment]
@donaldpipowitch nice idea! Yes it is possible, at least on ES6.

I'm started this project based on [Haskell syntax](https://www.haskell.org/tutorial/patterns.html), but your example can be useful for newcomers in functional programming to understand the last parameter tail concept.
